### PR TITLE
shipyard: introduce two new modes

### LINKED ISSUE #261: Design the shipyard page using airtable api
Design the page using the UI present in Figma: https://www.figma.com/file/sfhzVKGQkewApNXs6RvsHP/FOSSCU?type=design&node-id=4023-26&mode=design&t=4w1Vce8liXx4WioP-0.
 Additionally, you need to fetch data from the Airtable API using the Airtable SDK. 
This issue is open to discussion.

### PR DESCRIPTION
**Pull request by YASH-YADAV-dynamo**
This is a draft pr
Made frontend of shipyard in two modes when shipyard is happening and when its not.

This PR fixes #261 

Screenshot from 2024-04-19 10-12-43

Screenshot from 2024-04-19 10-12-28

Screenshot from 2024-04-19 10-12-21

### CODE REVIEW

**Comment by codecShivam** [comment]
Any updates on the PR? It's been over 2 weeks since it was opened.

**Review by A91y — CHANGES_REQUESTED** [review]
Try using Some better naming convention, rather than shipyard_no & shipyard_yes

**Comment by codecShivam** [comment]
Hey @YASH-YADAV-dynamo, focus on creating reusable components with multiple parts. This will help keep the codebase clean and organized. Additionally, consider defining data types for your various fields.

**Review by codecShivam — CHANGES_REQUESTED** [review]
Hey @YASH-YADAV-dynamo, focus on creating reusable components with multiple parts. This will help keep the codebase clean and organized. Additionally, consider defining data types for your various fields.

**Comment by YASH-YADAV-dynamo** [comment]
yeah sure

**Comment by codecShivam** [comment]
> yeah sure

@YASH-YADAV-dynamo are you working on it?

**Comment by YASH-YADAV-dynamo** [comment]
Yeahh

**Pull request closed without merging**
