### PR TITLE
Created landing page

### LINKED ISSUE #257: Design the landing page
Here is the Figma design for the landing page: https://www.figma.com/file/sfhzVKGQkewApNXs6RvsHP/FOSSCU?type=design&node-id=2001-1545&mode=design&t=27LpQZYFe8wnKmXU-0

drop your queries here so that I can assist you with development

### PR DESCRIPTION
**Pull request by piyusesh**
**Description**

This PR fixes #257

### CODE REVIEW

**Comment by piyusesh** [comment]
@codecShivam  this is how it looks
image
image
image
image
image

**Review by A91y — CHANGES_REQUESTED** [review]
image

Background element seem to overlap with the nav.

image


Same here too.

**Comment by piyusesh** [comment]
overlapping fixed

image

**Comment by piyusesh** [comment]
@codecShivam check I've added responsiveness to the page

**Review by codecShivam — CHANGES_REQUESTED** [review]
### Issue 1: Padding Adjustment

Needs some padding from the x direction

Needs some padding adjustment in the x-direction to enhance the visual spacing.

---

### Issue 2: Overlapping Content

This looks overlapped, give some gap

The content looks overlapped. Please add some gap between the elements to prevent overlapping.

---

### Issue 3: Background Image Visibility

The background image is not visible on the smaller screen

The background image is not visible on smaller screens. Ensure the background image is responsive and visible across different screen sizes.

---

### Issue 4: Responsive Layout

Work on this part wrap it in a way that on decreasing screen one element should go below and aligned to the center also change the text size for different screens

Wrap the elements in a way that, on decreasing the screen size, one element should go below and be aligned to the center. Also, adjust the text size for different screen sizes to maintain readability and alignment.

---

### Issue 5: Text Visibility

The text is not visible

The text is not visible. Improve the text alignment or background to enhance visibility.

---

### General Suggestions for Improvement

- **Breakpoints:** Focus on creating three breakpoints to handle different screen sizes. Adjust sizes, alignments, and spacing accordingly.
- **Text Size:** Ensure text sizes are responsive and legible on all devices.
- **Alignment:** Maintain proper alignment to ensure elements do not overlap and are visually appealing.


---

### Additional Suggestion

To ensure the design is properly viewed on all screens and devices, use the extension available at [https://mobileview.io/](https://mobileview.io/).

Excellent work, @piyusesh!

**Comment by piyusesh** [comment]
@codecShivam lmk if more improvements are needed

**Comment by Mr-Sunglasses** [comment]
> @codecShivam lmk if more improvements are needed

@codecShivam Review it ASAP

**Comment by codecShivam** [comment]
> > @codecShivam lmk if more improvements are needed
> 
> @codecShivam Review it ASAP

Yeah, will review it by today.

**Comment by codecShivam** [comment]
> @codecShivam lmk if more improvements are needed

everything lgm!! 
Just use the next/Image and remove this warning by providing width and height to it
image

**Comment by codecShivam** [comment]
lgm!! 
The warning is not resolved yet
take ref from here: https://nextjs.org/docs/pages/building-your-application/optimizing/images

**Comment by piyusesh** [comment]
@codecShivam done

**Comment by codecShivam** [comment]
Thanks! @piyusesh 
cc: @A91y

**Pull request merged**
